Copyname: bulk-rnaseq-longbench

channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  # Core tools with specific versions
  - python=3.10.8
  - nextflow=24.10.5
  - minimap2=2.28
  - samtools=1.9
  - oarfish=0.6.5